name: Nightly Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.2597+252c20310

    - run: |
        sudo apt-get update
        sudo apt-get install -y xorriso

    - run: |
        zig build -Ddevice=q35
        mv ./zig-out/iso/violet.iso ./violet-q35.iso

    - run: |
        zig build -Ddevice=virt
        mv ./zig-out/iso/violet.iso ./violet-virt.iso

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "nightly build"
          files: |
            violet-q35.iso
            violet-virt.iso
