name: Nightly Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso
        wget https://ziglang.org/builds/zig-linux-x86_64-0.14.0-dev.2597+252c20310.tar.xz -O zig.tar.xz
        tar -xf zig.tar.xz
        mv zig-linux-x86_64-* /usr/local/zig
        sudo ln -s /usr/local/zig/zig /usr/local/bin/zig

    - name: q35 build
      run: |
        zig build -Ddevice=q35
        mv ./zig-out/iso/violet.iso ./violet-q35.iso

    - name: virt build
      run: |
        zig build -Ddevice=virt
        mv ./zig-out/iso/violet.iso ./violet-virt.iso

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "nightly build"
          files: |
            violet-q35.iso
            violet-virt.iso
